school/results/urls.py
from .views import Homepage
from django.urls import path,re_path
from django.conf import settings



from .views import StudentDetails, StudentAdd, ResultUpdate, StudentUpdateView, StudentAddmarks, student_add_marks, Pdf, SubjectSeaechView, SubjectDetailView, AllRankViewSearch, TeacherAllView, TeacherDetailView,SummaryView, StudentDataSheetPdf
urlpatterns = [
    path('', Homepage.as_view(), name='home'),

    path('subject-search/', SubjectSeaechView.as_view(), name='subject_search'),

    path('class_wise_rank_search/', AllRankViewSearch.as_view(
        template_name='results/all_rank_search.html'), name='all_rank_search'),

    re_path(r'^(?P<pk>\d+)/subject-detail/$', SubjectDetailView.as_view(), name='subject_details'),

    re_path(r'^(?P<pk>\d+)/student-result-details/$', StudentDetails.as_view(), name='std_details'),

    path('student_add/', StudentAdd.as_view(), name='std_add'),
    re_path(r'student_update/(?P<pk>\d+)/$', StudentUpdateView.as_view(), name='std_update'),

    re_path(r'student_marks_add/(?P<pk>\d+)/$', StudentAddmarks.as_view(), name='std_add_marks'),


    re_path(r"std_add_marks_func/(?P<pk>\d+)/$", student_add_marks, name='stdAdd_marks'),

    re_path(r"std_marks_update/(?P<pk>\d+)/$",ResultUpdate.as_view(), name='stdmarks_update'),

    re_path(r'^(?P<pk>\d+)/get-print-result-sheet/',Pdf.as_view(), name='pdf'),
    re_path(r'^(?P<pk>\d+)/get-class-result-sheet/', StudentDataSheetPdf.as_view(), name='class_wise_pdf'),

    path('teacher_list/', TeacherAllView.as_view(), name='teacher_list'),

    re_path(r'^(?P<pk>\d+)/teachers-profile/', TeacherDetailView.as_view(), name='teacher_detail'),

    path('summary/', SummaryView.as_view(), name='summary'),
    

    
]

school/school/urls.py
from django.contrib import admin
from django.urls import include, path, re_path
from results.views import Homepage, RankListView
from results.api.views import UserViewSet
from django.contrib.auth import views as auth_views

from rest_framework import routers
from django.conf import settings
from django.conf.urls.static import static

#router = routers.DefaultRouter()
#router.register(r'users', UserViewSet)





#from django.contrib.auth import login
#from django.contrib.auth import authenticate, login
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Homepage.as_view(), name='home_app'),
    path('results/', include('results.urls')),
    #path('login/', auth_views.login, name='login1'),
    path('results/', include('django.contrib.auth.urls')),
    path('api/', UserViewSet.as_view(), name='api'),
    #re_path(r'api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    path('all-school-rank/',RankListView.as_view() , name='rank'),

]

handler404 = 'results.views.ErrorPage'

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
school_name = 'Fulhata Secondary School'

# default: "Django Administration"
admin.site.site_header = school_name+' Admin Panel'
# default: "Site administration"
admin.site.index_title = school_name+' Administration '
admin.site.site_title = school_name+' adminsitration'

school/results/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.contrib.auth.models import AbstractUser
from .grade_sheet import SubjectGrade, SubjectGradePoint
from django.utils import timezone

from django.db.models import Avg, Count, Min, Sum


STD_CLASS = (
    ('6', 'Six'),
    ('7', 'Seven'),
    ('8', 'Eight'),
    ('9', 'Nine'),
    ('10', 'Ten'),
)


STD_GENDER = (
    ('MALE', 'Male'),
    ('FEMALE', 'Female'),
)

STD_GROUP = (
        ('S', 'Science'),
        ('B', 'Business Studies'),
        ('H', 'Humatics'),
        ('G', 'General'),
)


REGULAR = 'R'
OPTIONAL = 'O'
EXTRA='E'

SUBJECT_TYPE_CHOICE = (
        (REGULAR, 'REGULAR'),
        (OPTIONAL, 'OPTIONAL'),
        (EXTRA, 'EXTRA'),
)









class CustomUser(AbstractUser):
    name=models.CharField('Full Name',max_length=100)



class StdCommon(models.Model):
    pub_date = models.DateTimeField(auto_now_add=True)
    update_date = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True



class StdClass(models.Model):
    std_class_L=models.CharField('Class', max_length=10, default='Six')
    std_class_N=models.IntegerField('Class', default=6)

    def __str__(self):
        return self.std_class_L




class SubjectTecher(StdCommon):
    teacher_name=models.CharField('Teacher Name', max_length=100)
    teach_phone_number=models.IntegerField('Mobile Number')
    teach_major_subject=models.CharField('Subject Name: ', max_length=100)


    def __str__(self):
        return self.teacher_name








class StdSubject(StdCommon):


    subject_name = models.CharField('Subject Name', max_length=100)
    teacher=models.ForeignKey(SubjectTecher, on_delete=models.CASCADE, related_name='teacher')
    subject_group = models.CharField(
        'Subject Group', choices=STD_GROUP, default='G', max_length=10)

    subject_code=models.CharField('Subject Code', max_length=10)

    std_subject_class=models.ForeignKey(StdClass, on_delete=models.CASCADE)

    subjet_class = models.CharField(
        'Subject Class', max_length=2, choices=STD_CLASS, default='6')
    subject_type = models.CharField(
        'Subject Type', max_length=1, default=REGULAR, choices=SUBJECT_TYPE_CHOICE)
    subject_full_marks = models.DecimalField(
        'Full Marks', max_digits=5, decimal_places=2, default=100,blank=True, null=True)



    subject_theory_full_marks = models.FloatField('Theory Marks', blank=True, null=True)
    subject_mcq_full_marks = models.FloatField('MCQ', blank=True, null=True)
    subject_practical_marks = models.FloatField('Practical', blank=True, null=True)
    subject_total_marks = models.FloatField('Total Marks', blank=True, null=True, help_text='Plz dont input any number')

    '''
        Bangla and English first 2nd part marks added
    '''

    first_part_name = models.CharField('First Subject Name শুধু বাংলা ও ইংরেজীর জন্য', max_length=100, blank=True, null=True)
    first_part_theory_full_marks = models.FloatField('First Part Theory Marks শুধু বাংলা ও ইংরেজীর জন্য', blank=True, null=True)
    first_part_mcq_full_marks = models.FloatField('First Part MCQ Marks শুধু বাংলা ও ইংরেজীর জন্য', blank=True, null=True)

    second_part_name = models.CharField('Second Subject Name শুধু বাংলা ও ইংরেজীর জন্য', max_length=100, blank=True, null=True)
    second_part_theory_full_marks = models.FloatField(
        'Second Part Theory Marks শুধু বাংলা ও ইংরেজীর জন্য', blank=True, null=True)
    second_part_mcq_full_marks = models.FloatField('Second MCQ Marks শুধু বাংলা ও ইংরেজীর জন্য', blank=True, null=True)


    first_second_full_marks = models.FloatField('1st and 2nd Part Total marks শুধু বাংলা ও ইংরেজীর জন্য', blank=True, null=True)






    subject_form_searh_name=models.CharField('Subject Search Form name', max_length=500, blank=True, null=True)


    def __str__(self):
        return self.subject_name+' Class '+self.subjet_class+' '+' '+self.subject_type+' Code '+self.subject_code


    def save(self, *args, **kwargs):
        subject_form_searh_name=self.subject_name+' Class '+self.subjet_class+' '+' '+self.subject_type+' Code '+self.subject_code

        self.subject_form_searh_name=subject_form_searh_name


        try:
            self.subject_full_marks = self.subject_theory_full_marks
            theory_full=self.subject_theory_full_marks
        except:
            self.subject_full_marks = 0
            self.subject_theory_full_marks=None
            theory_full=0

        if self.subject_theory_full_marks == None:
            self.subject_theory_full_marks = None


        '''
        MCQ Marks added
        '''
        try:
            if self.subject_full_marks==None:
                self.subject_full_marks=0
            self.subject_full_marks = self.subject_full_marks + self.subject_mcq_full_marks
        except:
            if self.subject_full_marks==None:
                self.subject_full_marks=0
            self.subject_full_marks = self.subject_full_marks


        '''

        Practical Marks

        '''

        try:
            self.subject_full_marks = self.subject_full_marks + self.subject_practical_marks
        except:
            self.subject_full_marks = self.subject_full_marks

        self.subject_total_marks = self.subject_full_marks


        if self.subject_total_marks == None or self.subject_total_marks ==0:
            '''
            First and 2nd part adding marks

        '''
            try:
                self.first_second_full_marks=self.first_part_theory_full_marks
                try:
                    self.first_second_full_marks = self.first_second_full_marks+ self.first_part_mcq_full_marks
                except:
                    self.first_second_full_marks = self.first_second_full_marks
            except:
                self.first_second_full_marks = self.first_second_full_marks

            if self.first_second_full_marks != None:
                try:
                    self.first_second_full_marks = self.first_second_full_marks + self.second_part_theory_full_marks

                except:
                   self.first_second_full_marks = self.first_second_full_marks


                try:
                    self.first_second_full_marks = self.first_second_full_marks+ self.second_part_mcq_full_marks
                except:
                    self.first_second_full_marks = self.first_second_full_marks

                self.subject_total_marks = self.first_second_full_marks

            elif self.first_second_full_marks == None:
                self.first_second_full_marks == None

            self.subject_total_marks = self.subject_total_marks
            self.subject_full_marks=self.subject_total_marks



        super(StdSubject, self).save(*args, **kwargs) # Call the real save() method

    class Meta:
        verbose_name = ("Subject")
        verbose_name_plural = ("Subject")
        ordering = ['subject_code']






Exam_Name=(
    ('TR','True'),
    ('FL','False'),
)


#Define Examination Name
#it will return exam name with year
#year reaturn automaticlly
class ExamName(StdCommon):
    exam_name=models.CharField('Exam Name', max_length=100)
    subject_name=models.ManyToManyField(StdSubject)
    subject_class=models.ManyToManyField(StdClass)
    subject_piority=models.CharField(max_length=5, choices=Exam_Name, default=True)


    def __str__(self):
        return "%s %s" % (self.exam_name, self.pub_date.year)

class StudentInfo(StdCommon):

    std_name = models.CharField('Student Name',max_length=100, help_text='Type only student Full Name like as Nazmul Islam or Nazrul Islam', blank=True, null=True)
    #std_mobile_num=models.IntegerField("Mobile Number", null=True)
    #std_father_name=models.CharField("Father's Nmae", max_length=250, null=True)
    #std_mother_name=models.CharField("Mother's Nmae", max_length=50, null=True, blank=True)
    #std_address=models.CharField("Address", max_length=150, null=True, blank=True)

    #std_subject_class=models.ForeignKey(StdClass, on_delete=models.CASCADE, default=6)
    std_class = models.CharField('Student Class',max_length=2, choices=STD_CLASS, default=10, help_text='Select a class')
    std_roll = models.IntegerField('Roll Number',help_text='Type Student Roll Number (Only Number)')
    std_group=models.CharField('Group', choices=STD_GROUP, max_length=1, default='G')
    std_gender=models.CharField('Gender', max_length=10, choices=STD_GENDER, default='MALE')
    #std_subjects = models.ManyToManyField(StdSubject)


    std_total_marks = models.FloatField('Total Marks', default=0, blank=True, null=True)
    std_marks_with_fail_sub = models.FloatField(
        'Total Marks', default=0, blank=True, null=True)

    std_gpa = models.CharField('GPA', max_length=50,default='F', blank=True, null=True)

    std_grade_point_total_sum=models.FloatField('Total Avg Number per Subject', blank=True, null=True) # toal grade point sum

    std_grade_point_total_subject_avg = models.FloatField(
        'Total GPA', blank=True, null=True) #avg gradepoint

    std_fail_subject=models.IntegerField('Fail Subject', blank=True, null=True)


    school_rank=models.IntegerField('Student Rank in School',default=0, blank=True, null=True)
    class_rank = models.IntegerField(
        'Student Rank in Class', default=0, blank=True, null=True)

    std_gradepoint_without_opt_sub=models.FloatField('Without Opt Subject GPA', blank=True, null=True)


    def __str__(self):
        return f"{self.std_name}, Class:{self.std_class}, Roll:{self.std_roll}, Group:{self.std_group}, Gender:{self.std_gender}"

    class Meta:
            verbose_name = ("Student Detail")
            verbose_name_plural = ("Student Detail's")
            ordering = ['std_roll']


    def total_marks_sum(self):
        std_id = self.id
        x = Marks.objects.filter(std_name=std_id, subject_name__subject_type__exact='R').aggregate(
            total_number=Sum('subject_marks')).get('total_number', 0)

school/results/forms.py
from django import forms
from .models import StudentInfo, Marks, StdSubject
from django.forms import inlineformset_factory

class ProfileSearchForm(forms.Form):
    std_class = forms.CharField(required=False)




class AddStudentInfo(forms.ModelForm):
    class Meta:
        model=StudentInfo
        fields=("__all__")



class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model=StudentInfo

        fields=("__all__")


class StudentSubjectGPAForm(forms.ModelForm):
    class Meta:
        model = Marks

        exclude = ('std_name', 'subject_gpa',
                   'subject_gradepoint', 'std_result')


class StudentSubjectGPAFormAdd(forms.ModelForm):
    class Meta:
        model = Marks
        exclude = ('std_name','subject_gpa',
                   'subject_gradepoint', 'std_result')

    def __init__(self, *args, **kwargs):
        super(StudentSubjectGPAFormAdd, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['subject_marks'].queryset = StudentInfo.objects.filter(
                std_name__exact=self.instance.id)


class Addmarks(forms.Form):
   #students = forms.ModelChoiceField(queryset=StudentInfo.objects.get(pk=27))
   subject = forms.ModelChoiceField(queryset=StdSubject.objects.all())
   marks = forms.IntegerField()





''

class ResultSearchForm(forms.Form):
    STD_CLASS = (
    ('6', 'Six'),
    ('7', 'Seven'),
    ('8', 'Eight'),
    ('9', 'Nine'),
    ('10', 'Ten'),
)

    STD_GENDER = (
    ('MALE', 'Male'),
    ('FEMALE', 'Female'),
    )

    STD_GROUP = (
        ('S', 'Science'),
        ('B', 'Business Studies'),
        ('H', 'Humatics'),

    )


    std_roll_form = forms.IntegerField(label="ক্রমিক নম্বর",min_value=1, max_value=99, widget=forms.TextInput({"placeholder":"আপনার  শ্রেনীর রোল নম্বর দিন"}))
    std_class_form = forms.ChoiceField(choices=STD_CLASS, label="দয়া করে শ্রেনী নির্বাচন করুন")


    def __init__(self, *args, **kwargs):
        super(ResultSearchForm, self).__init__(*args, **kwargs)

        self.initial['std_class_form'] = '10'






class SubjectSearchForm(forms.Form):
    STD_CLASS = (
        ('6', 'Six'),
        ('7', 'Seven'),
        ('8', 'Eight'),
        ('9', 'Nine'),
        ('10', 'Ten'),
    )
    subject_name=forms.ModelChoiceField(queryset=StdSubject.objects.all(), label='Select Subject Name', empty_label=None)
    subject_class = forms.ChoiceField(choices=STD_CLASS, label="Select Class")


    def __init__(self, *args, **kwargs):
        super(SubjectSearchForm, self).__init__(*args, **kwargs)

        self.initial['subject_class'] = '10'


class ClassSearchForm(forms.Form):
    STD_CLASS = (
        ('6', 'Six'),
        ('7', 'Seven'),
        ('8', 'Eight'),
        ('9', 'Nine'),
        ('10', 'Ten'),
    )

    student_class = forms.ChoiceField(choices=STD_CLASS, label="দয়া করে শ্রেনী নির্বাচন করুন")


    def __init__(self, *args, **kwargs):
        super(ClassSearchForm, self).__init__(*args, **kwargs)

        self.initial['student_class'] = '10'

school/results/api/views.py
from .serializers import StudentSerializers
from results.models import StudentInfo
from rest_framework import viewsets
from rest_framework import generics
from rest_framework.permissions import IsAdminUser



class UserViewSet(generics.ListAPIView):
    """
    API endpoint that allows users to be viewed or edited.
    """
    queryset = StudentInfo.objects.all().order_by('-std_grade_point_total_subject_avg','std_roll')
    serializer_class = StudentSerializers
    #permission_classes = (IsAdminUser,)

school/results/templates/results/all_rank_search.html
{% extends "results/base.html" %}
{% load crispy_forms_tags %}
{% block main_content %}

{% load humanize %}



<div class="row">
<div class="col-md-12 ">
<h1 style="text-align:center" class="mx-auto">Yearly/Test Examination 2019 Class Wise Position Search </h1>
</div>

<div class="col-md-3 offset-md-4  centered">

    <form action="" method="POST">
        {% csrf_token %} {{form | crispy}}
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>

<hr>




<div class="col-lg-12 centered">
    <div class="card">

        <div class="card-body">
            {% if std_search %}


<!--<a href="{% url 'class_wise_pdf' class_name %}">Download</a>-->




<h2 class="mx-auto" style="width:550px;font-size:25px">Class {{class_name}} Position List and analysis</h2>



<div class="row">
    <div class="col-md-12">
        <div class="div">
            <div class="progress" style="height:40px; margin-bottom:20px">
                <div class="progress-bar  progress-bar-striped progress-bar-animated  bg-success" style="width:{{pass_percent|floatformat:'0'}}%">
                    <b style="font-size:12px">Pass {{pass_percent|floatformat:'2'}}%</b>
                </div>
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-danger" style="width:{{fail_percent|floatformat:'0'}}%">
                    <b style="font-size:12px">Fail {{fail_percent|floatformat:'2'}}%</b>
                </div>

            </div>

        </div>
    </div>
</div>


<div class="div">
    <div class="row">

        <div class="col-md-6">
            <table class="table mx-auto" style="width:400px">


            <tr class="table-danger">
                <td>Class: </td>
                <td>{{class_name}}</td>

            </tr>





            <tr class="table-primary">
                <td>Total Examinee | class {{class_name}}</td>
                <td>{{std_search_count}}  </td>

            </tr>

            <tr class="table-info">
                <td>Total Passed</td>
                <td>{{total_pass_std_count}}

                <span class="badge badge-success">{{pass_percent|floatformat:'2'}}%</span>
            </td>

            </tr>


            <tr class="table-danger">
                <td>Total Fail</td>
                <td>{{fail_std_count}}
                <span class="badge badge-danger">{{fail_percent|floatformat:'2'}}%</span>

                </td>

            </tr>



            <tr class="table-success">
                <td>Total Male</td>
                <td>{{total_male_list}}</td>

            </tr>


            <tr class="table-success">
                <td>Total Female</td>
                <td>{{total_female_list}}</td>

            </tr>



            <tr class="table-danger">
                <td>Male pass</td>
            <td>{{pass_std_count_male}}</td>

            <tr class="table-danger">
                <td>Female pass</td>
                <td>{{pass_std_count_female}}</td>
            </tr>

            <tr class="table-danger">
                <td>Male Fail</td>
                <td>{{male_std_fail}}</td>
            </tr>


            <tr class="table-danger">
                <td>Female Fail</td>
                <td>{{female_std_fail}}</td>
            </tr>



        </table>
    </div>



<div class="col-md-6">
    <table class="table mx-auto" style="width:400px">





        <tr class="table-success">
            <td>A+</td>
            <td>{{std_gpa_aplus}}</td>

        </tr>
        <tr class="table-info">
            <td>A</td>
            <td>{{std_gpa_a}}</td>

        </tr>
        <tr class="table-warning">
            <td>A-</td>
            <td>{{std_gpa_a_minus}}</td>

        </tr>
        <tr class="table-danger">
            <td>B</td>
            <td>{{std_gpa_b}}</td>

        </tr>

        <tr class="table-info">
            <td>C</td>
            <td>{{std_gpa_c|floatformat}}</td>

        </tr>

        <tr class="table-info">
            <td>D</td>
            <td>{{std_gpa_d|floatformat}}</td>

        </tr>

        <tr class="table-warning">
            <td>Average Gradepoint (GPA)</td>
            <td>{{std_search_avg_gradepoint|floatformat:'2'}}</td>

        </tr>

    </table>
</div>









        </div>
    </div>
</div>



<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12 mx-auto ">

        <div class="div">





            <table class="table table-hover table-bordered">
                <thead>
                    <tr>
                        <th>SL</th>
                        <th>Class Position</th>
                        <th>Student Name</th>
                        <th>Roll</th>
                        <th>Position Status</th>


                        <!--<th>School Rank</th>-->
                        <th>Class</th>

                        <th>GPA</th>
                        <th>Marks</th>
                    </tr>
                </thead>
                <tbody>
                    {% for std in std_search%}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{std.class_rank|ordinal}} <!--<a href="{% url 'pdf' std.id%}" target="_blank"> print</a>--></td>


                        {% if std.std_fail_subject >= 1 %}
                        <td >
                        <a style="color:red" href="{% url 'std_details' std.id%}">{{std.std_name}}</a>
                        <span class="badge badge-danger">F{{std.std_fail_subject}}</span>
                        </td>
                        {% else %}
                        <td>
                        <a href="{% url 'std_details' std.id%}">{{std.std_name}}</a>
                        </td>
                        {% endif %}






                        <td>{{std.std_roll}}</td>

                        {% if std.std_roll > std.class_rank %}
                        <td style="color:#3498db">
                            <i class="fas fa-arrow-up"></i>Position Up
                        </td>

                        {% elif std.std_roll < std.class_rank%}

                        <td style="color:red"><i class="fas fa-arrow-down"></i>  Position Down </td>

                        {% elif std.std_roll == std.class_rank %}

                        <td style="font-size:14px;color:green"> Position label
                            <i class="fas fa-arrows-alt-v"></i>
                        </td>

                        {% endif %}






                        <!--<td>{{std.school_rank|ordinal}}</td>-->

                        <td>{{std.get_std_class_display}}</td>


                        {% if std.std_fail_subject >= 1 and std.std_gpa != 'Withheld' %}
                        <td style="color:red;font-size:12px">
                            Fail {{std.std_fail_subject}} Subject
                        </td>
                        {% elif std.std_gpa == 'Withheld' %}
                        <td style="color:red;font-size:12px">
                            Withheld (absent)
                        </td>
                         {% else %}
                        <td>
                            {% if std.std_grade_point_total_subject_avg > 5 %}
                            {{std.std_grade_point_total_subject_avg|floatformat:0}}.00
                            {% else %}
                            {{std.std_grade_point_total_subject_avg|floatformat:'2'}}
                            {% endif %}
                        </td>
                        {% endif %}





                        <td>{{std.std_total_marks|floatformat}}</td>



                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>




{% block pagination %} {% if is_paginated %}
<div class="pagination">
    <ul class="pagination mx-auto">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}">previous</a>
        </li>
        {% endif %}

        <li class="page-item active">
            <a class="page-link" href="#"> Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</a>
        </li>

        </li>



        {% if page_obj.has_next %}
        <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}">next</a>
        </li>
        {% endif %}
        </li>
    </ul>
    {% endif %} {% endblock %}





            {% elif std_search == None %}

            <h4 style="text-align:center;font-size:15px;padding:10px; width:400px;margin:0 auto" class="card bg-dark text-white card-title ">Fulhata Secondary School Result Application</h4>


            {% else %}
            <h4 style="text-align:center;font-size:15px;padding:10px" class="card bg-danger text-white card-title">{{std_search.subject_name}} Not Found</h4>
            {% endif %}

        </div>
    </div>
</div>






</div>


{% endblock main_content %}

school/results/templates/results/std_add_marks_func.html
{% extends "results/base.html" %} {% load crispy_forms_tags %} {% block main_content %}

<h2>Hey this is work</h2>

<p>Gender: {{std.std_gender}}</p>
<p>Roll: {{std.std_roll}}</p>
<p>Class: {{std.std_class}}</p>
<p>Group: {{std.std_group}}</p>


<div class="col-md-6 offset-md-3  centered">
    <form action="" method="POST">
        {% csrf_token %} {{form | crispy}}

        <input type="submit" value="Add Your Subject" class="btn btn-primary">
    </form>
</div>
ff{{x}} {% endblock main_content %}

school/results/templates/results/std_marks_update.html
{% extends "results/base.html" %} {% block main_content %}


{{form}}


{% endblock main_content %}

school/results/templates/results/teacher_details.html
{% extends "results/base.html" %} 
{% block main_content %} 
{% load humanize %}

<div class="row">
    <div class="col-md-12">
    <h1>Teacher Name: {{ object.teacher_name }}</h1>
    <p>Phone Number: {{ object.teach_phone_number }}</p>
    <p class="card-text">{{object.teach_major_subject}}</p>
    <p style="font-size:5px">Published: {{ object.pub_date|naturaltime}}</p>



<div id="" class="">
<table class="table table-striped">
    <thead>
        <tr>
            <th>SL</th>
            <th>Subject Name</th>
            <th>Class/Group/Type</th>

            <th>
                <td>Theory</td>
                <td>MCQ</td>
                <td>Practical</td>

                <td>1st Part Theory</td>
                <td>1st Part MCQ</td>

                <td>2nd Part Theory</td>
                <td>2nd Part MCQ</td>
                
            </th>

            <th>Total Marks</th>
            
            
            
        </tr>
    </thead>
    <tbody>
        {% for sub in object.teacher.all %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>
                    {% if sub.get_subject_type_display == "REGULAR" %}
                    <button type="button" class="btn btn-success"><a style="color: #ffffff" href="{% url 'subject_details' sub.id %}">{{sub.subject_name}} </a></button>
                    
                    {% elif sub.get_subject_type_display == "OPTIONAL"%}
                    <button type="button" class="btn btn-info"><a style="color:#ffffff" href="{% url 'subject_details' sub.id %}">{{sub.subject_name}} </a></button>
    
                    {% else %}
    
                    <a style="color: #ffffff" href="{% url 'subject_details' sub.id %}">{{sub.subject_name}} </a>
    
                    {% endif %}
            </td>

            <td>
                <span style="font-size: 20px">{{sub.get_subjet_class_display}}</span> <span class="badge badge-info">{{sub.get_subject_group_display}}</span>

                {% if sub.get_subject_type_display == "REGULAR" %}
                <span class="badge badge-warning">{{sub.get_subject_type_display}}</span>
                
                {% elif sub.get_subject_type_display == "OPTIONAL"%}
                <span class="badge badge-dark">{{sub.get_subject_type_display}}</span>

                {% else %}

                {{sub.get_subject_type_display}}

                {% endif %}
            
            
            </td>
            <td>
                <td>{{sub.subject_theory_full_marks|floatformat}}</td>
                <td>{{sub.subject_mcq_full_marks|floatformat}}</td>
                <td>{{sub.subject_practical_marks|floatformat}}</td>
                <td>{{sub.first_part_theory_full_marks|floatformat}}</td>
                <td>{{sub.first_part_mcq_full_marks|floatformat}}</td>
                <td>{{sub.second_part_theory_full_marks|floatformat}}</td>
                <td>{{sub.second_part_mcq_full_marks|floatformat}}</td>
            </td>
            <td>
                {{sub.subject_full_marks|floatformat}}
            </td>
           
            
            
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>




    

        
        
      
    

    
</div>




{% endblock main_content %}